### ISSUE TITLE
Bug in C implementation.

### ISSUE THREAD

**Issue by ajtulloch** [marblestation/benchmark-leapfrog#9]
https://github.com/marblestation/benchmark-leapfrog/blob/773792a2bdb8a6dab2f7a143bed6e9c50ce6a0f5/c/leapfrog.c#L33-L35

This isn't correct, right? Shouldn't it be:

```
            double dx = x[i][0] - x[j][0];
            double dy = x[i][1] - x[j][1];
            double dz = x[i][2] - x[j][2];
```

**Comment by marblestation** [comment]
Thanks! Corrected by https://github.com/marblestation/benchmark-leapfrog/pull/3
